os:
  - linux
  - osx
  - windows
language: node_js
node_js:
  - '8'
  - '12'
  - '14'
  - '16'
before_install:
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export export CXX=g++-6; fi'
before_script:
  - export NPMVERSION=$(echo "$($(which npm) -v)"|cut -c1)
  - 'if [[ $NPMVERSION == 5 ]]; then npm install -g npm@5; fi'
  - npm -v
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - libbluetooth-dev
      - libudev-dev
script:
  - 'npm run test:package'
  - 'npm run test:integration'
